### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by cdplayer09** [haveachin/reddit-bot#23]
Every link just says "Reddit did not respond."

**Comment by haveachin** [comment]
It looks like Reddit started to block IPs of data centers. That means I can't host the bot an a VPS anymore. RIP until I find a solution.
![image](https://github.com/haveachin/reddit-bot/assets/30272106/fa4fc7aa-2ef2-4f76-815c-a7bea94f0afa)

**Comment by cdplayer09** [comment]
Thanks for the reply and thanks for making the bot! Hope there is a way in the future to fix it.

**Comment by haveachin** [comment]
Running on a microcontroller that is literal sitting on my desk for now. Expect it to be slower than before.  I'm gonna close this for now.
