### ISSUE TITLE
Support for Embedded media

### ISSUE THREAD

**Issue by 4kills** [haveachin/reddit-bot#8]
Embedded media cannot be automatically shown in a reddit post. The special sites (like youtube, gfycat...) need custom support for that. The following list tracks implementation and is expanded if needed: 

- [x] Youtube (support added in #7)
- [x] Gfycat
. . .

**Comment by haveachin** [comment]
Did #8 complete this issue?

**Comment by haveachin** [comment]
Bump @4kills
